title: Rupali Rajesh
description: LLMs | AI
remote_theme: mmistakes/minimal-mistakes@4.19.3
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Enable MathJax globally
head_scripts:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - jekyll-remote-theme
